spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/maikhir/ms-config-server.git
          clone-on-start: true
server:
  port: 8888
